/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.0
 **/

#ifndef __piperlcm_JointState_hpp__
#define __piperlcm_JointState_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>

#include "Time.hpp"

namespace piperlcm {

class JointState {
public:
  piperlcm::Time header;

  /**
   * LCM Type: string[7]
   */
  std::string name[7];

  /**
   * LCM Type: double[7]
   */
  double position[7];

  /**
   * LCM Type: double[7]
   */
  double velocity[7];

  /**
   * LCM Type: double[7]
   */
  double effort[7];

public:
  /**
   * Encode a message into binary form.
   *
   * @param buf The output buffer.
   * @param offset Encoding starts at thie byte offset into @p buf.
   * @param maxlen Maximum number of bytes to write.  This should generally be
   *  equal to getEncodedSize().
   * @return The number of bytes encoded, or <0 on error.
   */
  inline int encode(void *buf, int offset, int maxlen) const;

  /**
   * Check how many bytes are required to encode this message.
   */
  inline int getEncodedSize() const;

  /**
   * Decode a message from binary form into this instance.
   *
   * @param buf The buffer containing the encoded message.
   * @param offset The byte offset into @p buf where the encoded message starts.
   * @param maxlen The maximum number of bytes to read while decoding.
   * @return The number of bytes decoded, or <0 if an error occured.
   */
  inline int decode(const void *buf, int offset, int maxlen);

  /**
   * Retrieve the 64-bit fingerprint identifying the structure of the message.
   * Note that the fingerprint is the same for all instances of the same
   * message type, and is a fingerprint on the message type definition, not on
   * the message contents.
   */
  inline static int64_t getHash();

  /**
   * Returns "JointState"
   */
  inline static const char *getTypeName();

  // LCM support functions. Users should not call these
  inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
  inline int _getEncodedSizeNoHash() const;
  inline int _decodeNoHash(const void *buf, int offset, int maxlen);
  inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int JointState::encode(void *buf, int offset, int maxlen) const {
  int pos = 0, tlen;
  int64_t hash = getHash();

  tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  return pos;
}

int JointState::decode(const void *buf, int offset, int maxlen) {
  int pos = 0, thislen;

  int64_t msg_hash;
  thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
  if (thislen < 0)
    return thislen;
  else
    pos += thislen;
  if (msg_hash != getHash()) return -1;

  thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
  if (thislen < 0)
    return thislen;
  else
    pos += thislen;

  return pos;
}

int JointState::getEncodedSize() const {
  return 8 + _getEncodedSizeNoHash();
}

int64_t JointState::getHash() {
  static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
  return hash;
}

const char *JointState::getTypeName() {
  return "JointState";
}

int JointState::_encodeNoHash(void *buf, int offset, int maxlen) const {
  int pos = 0, tlen;

  tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  for (int a0 = 0; a0 < 7; a0++) {
    char *__cstr = const_cast<char *>(this->name[a0].c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &__cstr, 1);
    if (tlen < 0)
      return tlen;
    else
      pos += tlen;
  }

  tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->position[0], 7);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->velocity[0], 7);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->effort[0], 7);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  return pos;
}

int JointState::_decodeNoHash(const void *buf, int offset, int maxlen) {
  int pos = 0, tlen;

  tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  for (int a0 = 0; a0 < 7; a0++) {
    int32_t __elem_len;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__elem_len, 1);
    if (tlen < 0)
      return tlen;
    else
      pos += tlen;
    if (__elem_len > maxlen - pos) return -1;
    this->name[a0].assign(static_cast<const char *>(buf) + offset + pos, __elem_len - 1);
    pos += __elem_len;
  }

  tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->position[0], 7);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->velocity[0], 7);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->effort[0], 7);
  if (tlen < 0)
    return tlen;
  else
    pos += tlen;

  return pos;
}

int JointState::_getEncodedSizeNoHash() const {
  int enc_size = 0;
  enc_size += this->header._getEncodedSizeNoHash();
  for (int a0 = 0; a0 < 7; a0++) {
    enc_size += this->name[a0].size() + 4 + 1;
  }
  enc_size += __double_encoded_array_size(NULL, 7);
  enc_size += __double_encoded_array_size(NULL, 7);
  enc_size += __double_encoded_array_size(NULL, 7);
  return enc_size;
}

uint64_t JointState::_computeHash(const __lcm_hash_ptr *p) {
  const __lcm_hash_ptr *fp;
  for (fp = p; fp != NULL; fp = fp->parent)
    if (fp->v == JointState::getHash)
      return 0;
  const __lcm_hash_ptr cp = {p, JointState::getHash};

  uint64_t hash = 0x44a9606311343b5aLL + piperlcm::Time::_computeHash(&cp);

  return (hash << 1) + ((hash >> 63) & 1);
}

} // namespace piperlcm

#endif
